name: Lint and test
'on':
  push:
    branches:
      - main
  pull_request:

jobs:
  test_build_and_lint:
    runs-on: ubuntu-latest
    steps:
      - run: npm run lint:electron
      - run: npm run lint:renderer
      - run: npm run test
